@startuml FacadePatternClassDiagram

class Facade {
  -subsystemA : SubsystemClassA
  -subsystemB : SubsystemClassB
  -subsystemC : SubsystemClassC
  +operation() : void
}

class SubsystemClassA {
  +operationA() : void
}
note left of SubsystemClassA
  Subsystems may have complex
  relationships and functionalities.
end note


class SubsystemClassB {
  +operationB() : void
}

class SubsystemClassC {
  +operationC() : void
}

Facade --> SubsystemClassA : Uses
Facade --> SubsystemClassB : Uses
Facade --> SubsystemClassC : Uses

note right of Facade
  Facade provides a simple interface
  to the complex functionality
  of the subsystems.
end note


@enduml
