@startuml SingletonPatternClassDiagram

class Singleton {
  -static uniqueInstance: Singleton
  -Singleton()
  +static getInstance(): Singleton
}

note right of Singleton
  Singleton uses a private constructor
  and a private static instance variable.
  The getInstance() method ensures that
  only one instance is created and returned.
end note

@enduml
