@startuml ChainOfResponsibilityPatternSequenceDiagram

actor Client
participant Handler
participant ConcreteHandler1
participant ConcreteHandler2
participant Request

Client -> ConcreteHandler1: request
activate ConcreteHandler1

ConcreteHandler1 -> ConcreteHandler2: request
activate ConcreteHandler2
ConcreteHandler2 -> Request: handleRequest()
activate Request
Request --> ConcreteHandler2: response
deactivate Request
ConcreteHandler2 --> ConcreteHandler1: response
deactivate ConcreteHandler2
ConcreteHandler1 --> Client: response
deactivate ConcreteHandler1

@enduml
